[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# Goi /api/state se chay function state.js
[[redirects]]
  from = "/api/state"
  to = "/.netlify/functions/state"
  status = 200

[[redirects]]
  from = "/api/orders"
  to = "/.netlify/functions/orders"
  status = 200

[[redirects]]
  from = "/api/auth-config"
  to = "/.netlify/functions/auth-config"
  status = 200

[[redirects]]
  from = "/review"
  to = "/.netlify/functions/review"
  status = 200
